/* prettier-ignore */
/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router
// 请不要手动修改此文件，否则会导致优雅路由无法正常工作
// 如果需要修改，请在优雅路由配置文件中进行修改
// 这是自动生成的文件，请不要手动修改

//这里只能修改 handle 并且路由组作为布局路由组件 是不能有handle的

import type { ElegantConstRoute } from '@soybean-react/vite-plugin-react-router';

export const generatedRoutes: ElegantConstRoute[] = [
  {
    matchedFiles: ['root', '/src/pages/index.tsx', '/src/pages/loading.tsx', 'root'],
    name: 'root',
    path: '/',
    handle: { i18nKey: 'route.root', title: 'root', constant: true },
    children: [
      {
        matchedFiles: [null, null, null, null],
        name: '(backup)',
        children: [
          {
            matchedFiles: [null, '/src/pages/(backup)/about/index.tsx', null, null],
            name: '(backup)_about',
            path: '/about',
            handle: { i18nKey: 'route.(backup)_about', title: '(backup)_about' }
          },
          {
            matchedFiles: [null, '/src/pages/(backup)/function/index.tsx', null, null],
            name: '(backup)_function',
            path: '/function',
            handle: { i18nKey: 'route.(backup)_function', title: '(backup)_function' },
            children: [
              {
                matchedFiles: [null, '/src/pages/(backup)/function/event-bus/index.tsx', null, null],
                name: '(backup)_function_event-bus',
                path: '/function/event-bus',
                handle: { i18nKey: 'route.(backup)_function_event-bus', title: '(backup)_function_event-bus' }
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/hide-child/index.tsx', null, null],
                name: '(backup)_function_hide-child',
                path: '/function/hide-child',
                handle: { i18nKey: 'route.(backup)_function_hide-child', title: '(backup)_function_hide-child' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(backup)/function/hide-child/one/index.tsx', null, null],
                    name: '(backup)_function_hide-child_one',
                    path: '/function/hide-child/one',
                    handle: {
                      i18nKey: 'route.(backup)_function_hide-child_one',
                      title: '(backup)_function_hide-child_one'
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(backup)/function/hide-child/three/index.tsx', null, null],
                    name: '(backup)_function_hide-child_three',
                    path: '/function/hide-child/three',
                    handle: {
                      i18nKey: 'route.(backup)_function_hide-child_three',
                      title: '(backup)_function_hide-child_three'
                    }
                  },
                  {
                    matchedFiles: [null, '/src/pages/(backup)/function/hide-child/two/index.tsx', null, null],
                    name: '(backup)_function_hide-child_two',
                    path: '/function/hide-child/two',
                    handle: {
                      i18nKey: 'route.(backup)_function_hide-child_two',
                      title: '(backup)_function_hide-child_two'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/multi-tab/index.tsx', null, null],
                name: '(backup)_function_multi-tab',
                path: '/function/multi-tab',
                handle: { i18nKey: 'route.(backup)_function_multi-tab', title: '(backup)_function_multi-tab' }
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/request/index.tsx', null, null],
                name: '(backup)_function_request',
                path: '/function/request',
                handle: { i18nKey: 'route.(backup)_function_request', title: '(backup)_function_request' }
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/super-page/index.tsx', null, null],
                name: '(backup)_function_super-page',
                path: '/function/super-page',
                handle: { i18nKey: 'route.(backup)_function_super-page', title: '(backup)_function_super-page' }
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/tab/index.tsx', null, null],
                name: '(backup)_function_tab',
                path: '/function/tab',
                handle: { i18nKey: 'route.(backup)_function_tab', title: '(backup)_function_tab' }
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/toggle-auth/index.tsx', null, null],
                name: '(backup)_function_toggle-auth',
                path: '/function/toggle-auth',
                handle: { i18nKey: 'route.(backup)_function_toggle-auth', title: '(backup)_function_toggle-auth' }
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/function/use-request/index.tsx', null, null],
                name: '(backup)_function_use-request',
                path: '/function/use-request',
                handle: { i18nKey: 'route.(backup)_function_use-request', title: '(backup)_function_use-request' }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(backup)/multi-menu/index.tsx', null, null],
            name: '(backup)_multi-menu',
            path: '/multi-menu',
            handle: { i18nKey: 'route.(backup)_multi-menu', title: '(backup)_multi-menu' },
            children: [
              {
                matchedFiles: [null, '/src/pages/(backup)/multi-menu/first/index.tsx', null, null],
                name: '(backup)_multi-menu_first',
                path: '/multi-menu/first',
                handle: { i18nKey: 'route.(backup)_multi-menu_first', title: '(backup)_multi-menu_first' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(backup)/multi-menu/first/child/index.tsx', null, null],
                    name: '(backup)_multi-menu_first_child',
                    path: '/multi-menu/first/child',
                    handle: {
                      i18nKey: 'route.(backup)_multi-menu_first_child',
                      title: '(backup)_multi-menu_first_child'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(backup)/multi-menu/second/index.tsx', null, null],
                name: '(backup)_multi-menu_second',
                path: '/multi-menu/second',
                handle: { i18nKey: 'route.(backup)_multi-menu_second', title: '(backup)_multi-menu_second' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(backup)/multi-menu/second/child/index.tsx', null, null],
                    name: '(backup)_multi-menu_second_child',
                    path: '/multi-menu/second/child',
                    handle: {
                      i18nKey: 'route.(backup)_multi-menu_second_child',
                      title: '(backup)_multi-menu_second_child'
                    },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(backup)/multi-menu/second/child/home/index.tsx', null, null],
                        name: '(backup)_multi-menu_second_child_home',
                        path: '/multi-menu/second/child/home',
                        handle: {
                          i18nKey: 'route.(backup)_multi-menu_second_child_home',
                          title: '(backup)_multi-menu_second_child_home'
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(backup)/projects/index.tsx', null, null],
            name: '(backup)_projects',
            path: '/projects',
            handle: { i18nKey: 'route.(backup)_projects', title: '(backup)_projects' },
            children: [
              {
                matchedFiles: [null, '/src/pages/(backup)/projects/[pid]/index.tsx', null, null],
                name: '(backup)_projects_[pid]',
                path: '/projects/:pid',
                handle: { i18nKey: 'route.(backup)_projects_[pid]', title: '(backup)_projects_[pid]' },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(backup)/projects/[pid]/edit/index.tsx', null, null],
                    name: '(backup)_projects_[pid]_edit',
                    path: '/projects/:pid/edit',
                    handle: { i18nKey: 'route.(backup)_projects_[pid]_edit', title: '(backup)_projects_[pid]_edit' },
                    children: [
                      {
                        matchedFiles: [null, '/src/pages/(backup)/projects/[pid]/edit/[id].tsx', null, null],
                        name: '(backup)_projects_[pid]_edit_[id]',
                        path: '/projects/:pid/edit/:id',
                        handle: {
                          i18nKey: 'route.(backup)_projects_[pid]_edit_[id]',
                          title: '(backup)_projects_[pid]_edit_[id]'
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(backup)/user-center/index.tsx', null, null],
            name: '(backup)_user-center',
            path: '/user-center',
            handle: { i18nKey: 'route.(backup)_user-center', title: '(backup)_user-center' }
          }
        ],
        path: null
      },
      {
        matchedFiles: ['(base)', null, null, null],
        name: '(base)',
        children: [
          {
            matchedFiles: [null, '/src/pages/(base)/anke-agents/index.tsx', null, null],
            name: '(base)_anke-agents',
            path: '/anke-agents',
            handle: { i18nKey: 'route.(base)_anke-agents', title: '(base)_anke-agents' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/anke-conversation/index.tsx', null, null],
            name: '(base)_anke-conversation',
            path: '/anke-conversation',
            handle: { i18nKey: 'route.(base)_anke-conversation', title: '(base)_anke-conversation' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/anke-user/index.tsx', null, null],
            name: '(base)_anke-user',
            path: '/anke-user',
            handle: { i18nKey: 'route.(base)_anke-user', title: '(base)_anke-user' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/anke-user-groups/index.tsx', null, null],
            name: '(base)_anke-user-groups',
            path: '/anke-user-groups',
            handle: { i18nKey: 'route.(base)_anke-user-groups', title: '(base)_anke-user-groups' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/home/index.tsx', null, null],
            name: '(base)_home',
            path: '/home',
            handle: { i18nKey: 'route.(base)_home', icon: 'mdi:monitor-dashboard', order: 1, title: 'home' }
          },
          {
            matchedFiles: [null, '/src/pages/(base)/manage/index.tsx', null, null],
            name: '(base)_manage',
            path: '/manage',
            handle: {
              i18nKey: 'route.(base)_manage',
              icon: 'carbon:cloud-service-management',
              order: 8,
              roles: ['R_ADMIN'],
              title: 'manage'
            },
            children: [
              {
                matchedFiles: [null, '/src/pages/(base)/manage/config/index.tsx', null, null],
                name: '(base)_manage_config',
                path: '/manage/config',
                handle: { i18nKey: 'route.(base)_manage_config', title: '(base)_manage_config' }
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/role/index.tsx', null, null],
                name: '(base)_manage_role',
                path: '/manage/role',
                handle: {
                  i18nKey: 'route.(base)_manage_role',
                  icon: 'carbon:user-role',
                  order: 2,
                  roles: ['R_SUPER'],
                  title: 'manage_role'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/manage/role/[...slug].tsx', null, null],
                    name: '(base)_manage_role_[...slug]',
                    path: '/manage/role/*',
                    handle: {
                      i18nKey: 'route.(base)_manage_role_[...slug]',
                      hideInMenu: true,
                      title: '(base)_manage_role_[...slug]'
                    }
                  }
                ]
              },
              {
                matchedFiles: [null, '/src/pages/(base)/manage/user/index.tsx', null, null],
                name: '(base)_manage_user',
                path: '/manage/user',
                handle: {
                  i18nKey: 'route.(base)_manage_user',
                  icon: 'ic:round-manage-accounts',
                  keepAlive: true,
                  order: 1,
                  roles: ['R_ADMIN'],
                  title: 'manage_user'
                },
                children: [
                  {
                    matchedFiles: [null, '/src/pages/(base)/manage/user/[id].tsx', null, null],
                    name: '(base)_manage_user_[id]',
                    path: '/manage/user/:id',
                    handle: {
                      activeMenu: '/manage/user',
                      hideInMenu: true,
                      i18nKey: 'route.(base)_manage_user_[id]',
                      title: '(base)_manage_user_[id]'
                    }
                  }
                ]
              }
            ]
          }
        ],
        path: null
      },
      {
        matchedFiles: ['(blank)', null, null, null],
        name: '(blank)',
        children: [
          {
            matchedFiles: ['(blank)_login', '/src/pages/(blank)/login/index.tsx', null, null],
            name: '(blank)_login',
            path: '/login',
            handle: { i18nKey: 'route.(blank)_login', title: '(blank)_login', constant: true },
            children: [
              {
                matchedFiles: [null, '/src/pages/(blank)/login/code-login/index.tsx', null, null],
                name: '(blank)_login_code-login',
                path: '/login/code-login',
                handle: { i18nKey: 'route.(blank)_login_code-login', title: '(blank)_login_code-login', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/register/index.tsx', null, null],
                name: '(blank)_login_register',
                path: '/login/register',
                handle: { i18nKey: 'route.(blank)_login_register', title: '(blank)_login_register', constant: true }
              },
              {
                matchedFiles: [null, '/src/pages/(blank)/login/reset-pwd/index.tsx', null, null],
                name: '(blank)_login_reset-pwd',
                path: '/login/reset-pwd',
                handle: { i18nKey: 'route.(blank)_login_reset-pwd', title: '(blank)_login_reset-pwd', constant: true }
              }
            ]
          },
          {
            matchedFiles: [null, '/src/pages/(blank)/login-out/index.tsx', null, null],
            name: '(blank)_login-out',
            path: '/login-out',
            handle: { i18nKey: 'route.(blank)_login-out', title: '(blank)_login-out', constant: true }
          }
        ],
        path: null
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/403/index.tsx', null, null],
        name: '403',
        path: '/403',
        handle: { i18nKey: 'route.403', title: '403', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: '404',
        path: '/404',
        handle: { i18nKey: 'route.404', title: '404', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/500/index.tsx', null, null],
        name: '500',
        path: '/500',
        handle: { i18nKey: 'route.500', title: '500', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/iframe-page/index.tsx', null, null],
        name: 'iframe-page',
        path: '/iframe-page',
        handle: { i18nKey: 'route.iframe-page', title: 'iframe-page', constant: true }
      },
      {
        matchedFiles: [null, '/src/pages/_builtin/404/index.tsx', null, null],
        name: 'notFound',
        path: '*',
        handle: { i18nKey: 'route.notFound', title: 'notFound', constant: true }
      }
    ]
  }
];
